"""add max_try fields

Revision ID: 572dbbb59e17
Revises: baad66ccabfb
Create Date: 2026-04-13 15:11:40.539472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572dbbb59e17'
down_revision: Union[str, None] = 'baad66ccabfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('max_retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'max_retries')
    # ### end Alembic commands ###
